FROM python:3.8

# 各種命令を実行する際のカレントディレクトリを指定
WORKDIR /workdir

# poetry のインストール
RUN set -x && \
    curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
ENV PATH /root/.poetry/bin:$PATH

# Poetry は自動で virtualenv を作成し、そこに環境を構築するが Docker内に仮想環境を作ってもしょうがないので virtualenv 作成を falseとする
RUN poetry config virtualenvs.create false
